spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Store?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    user:
      name: test
      password: test
  mail:
    host: smtp.gmail.com
    username: dawidszewczyk12@gmail.com
    password: xcdsycjmzmajmigu
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
